name: Build Rust

on:
  push:
    branches:
      - main
    paths:
      - "rust/**"
      - ".github/workflows/rust.yaml"
      - "install_tooling.sh"
  workflow_call:
  workflow_dispatch:

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: dwin/devspace-containers/rust

defaults:
  run:
    working-directory: rust

jobs:
  rust:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 1.72-alpine
          - 1.72-bullseye
          - 1.71-alpine
          - 1.71-bullseye
          - 1.67-alpine
          - 1.67-bullseye
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: loft-sh/setup-devspace@main
      - run: devspace build --var TAG=${{ matrix.tag }}
