name: Build TypeScript

on:
  push:
    branches:
      - main
    paths:
      - "typescript/**"
      - ".github/workflows/typescript.yaml"
      - "install_tooling.sh"
  workflow_call:
  workflow_dispatch:

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: dwin/devspace-containers/typescript

defaults:
  run:
    working-directory: typescript

jobs:
  typescript:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 20-alpine
          - tag: 18-alpine
          - tag: 17-alpine
          - tag: 16-alpine

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: loft-sh/setup-devspace@main
      - run: devspace build --var TAG=${{ matrix.tag }}
